drop database if exists battle_of_races;

create database if not exists battle_of_races;

use battle_of_races;

create table WEAPONS (
WEAPON_ID INT AUTO_INCREMENT PRIMARY KEY,
WEAPON_NAME  VARCHAR(256),
WEAPON_POINTS INT,
WEAPON_IMAGE_PATH VARCHAR(256),
WEAPON_STRENGTH INT,
WEAPON_SPEED INT
);

create table WARRIORS(
WARRIOR_ID INT AUTO_INCREMENT PRIMARY KEY,
WARRIOR_NAME VARCHAR(256),
WARRIOR_IMAGE_PATH VARCHAR(256),
WARRIORS_RACE_ID INT
);

create table PLAYERS(
PLAYER_ID INT AUTO_INCREMENT PRIMARY KEY,
PLAYER_NAME VARCHAR(256)
);

create table RACES(
RACE_ID INT AUTO_INCREMENT PRIMARY KEY,
RACE_NAME VARCHAR(256),
RACE_POINTS INT,
RACE_HP INT,
RACE_STRENGTH INT,
RACE_DEFENSE INT,
RACE_AGILITY INT,
RACE_SPEED INT
);

create table WEAPONS_AVAILABLE(
WEAPON_ID INT,
RACE_ID INT
);

create table BATTLE(
BATTLE_ID INT AUTO_INCREMENT PRIMARY KEY,
PLAYER_ID INT,
WARRIOR_ID INT,
WARRIOR_WEAPON_ID INT,
OPPONENT_ID INT,
OPPONENT_WEAPON_ID INT,
INJURIES_CAUSED INT,
INJURIES_SUFFERED INT,
BATTLE_POINTS INT
);

/* ALTERS */
alter table WARRIORS
	add constraint FOREIGN KEY (WARRIORS_RACE_ID) REFERENCES RACES(RACE_ID);

alter table WEAPONS_AVAILABLE
	add constraint FOREIGN KEY (WEAPON_ID) REFERENCES WEAPONS(WEAPON_ID),
    add constraint FOREIGN KEY (RACE_ID) REFERENCES RACES(RACE_ID); 

alter table BATTLE
	add constraint FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID),
    add constraint FOREIGN KEY (WARRIOR_ID) REFERENCES WARRIORS(WARRIOR_ID),
    add constraint FOREIGN KEY (WARRIOR_WEAPON_ID) REFERENCES WEAPONS(WEAPON_ID),
    add constraint FOREIGN KEY (OPPONENT_ID) REFERENCES WARRIORS(WARRIOR_ID),
    add constraint FOREIGN KEY (OPPONENT_WEAPON_ID) REFERENCES WEAPONS(WEAPON_ID);
